version: "3.8"
services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./shop.sql:/docker-entrypoint-initdb.d/shop.sql
volumes:
  db_data:
